use std::future::Future;

use crate::bytes::DynamicByteBuffer;
use crate::flow::error::FlowControllerError;

/// Trait for managing packet flow with encryption and decoy traffic.
/// Methods take `Arc<Self>` to enable spawning background tasks without requiring `Sync`.
pub trait FlowManager {
    /// Send a packet through the flow manager.
    /// If `generated` is true, this is a decoy packet generated by the flow manager.
    fn send_packet(&self, packet: DynamicByteBuffer, generated: bool) -> impl Future<Output = Result<(), FlowControllerError>> + Send;

    /// Receive a packet from the flow manager.
    fn receive_packet(&self, packet: DynamicByteBuffer) -> impl Future<Output = Result<DynamicByteBuffer, FlowControllerError>> + Send;
}
