use std::future::Future;
use std::sync::Arc;

use log::{debug, info};
use rand::Rng;

use crate::bytes::{ByteBuffer, ByteBufferMut, DynamicByteBuffer};
use crate::cache::CachedValue;
use crate::crypto::{CryptoError, ObfuscationTranscript};
use crate::flow::config::FlowConfig;
use crate::flow::error::FlowControllerError;
use crate::settings::consts::TAILOR_LENGTH;
use crate::tailor::{IdentityType, PacketFlags, Tailor};
use crate::utils::random::get_rng;

/// Trait for managing packet flow with encryption and decoy traffic.
pub trait FlowManager {
    /// Send a packet through the flow manager.
    /// If `generated` is true, this is a decoy packet generated by the flow manager.
    fn send_packet(&self, packet: DynamicByteBuffer, generated: bool) -> impl Future<Output = Result<(), FlowControllerError>> + Send;

    /// Receive a packet from the flow manager.
    fn receive_packet(&self, packet: DynamicByteBuffer) -> impl Future<Output = Result<DynamicByteBuffer, FlowControllerError>> + Send;
}

impl<T: FlowManager + Send + Sync> FlowManager for Arc<T> {
    fn send_packet(&self, packet: DynamicByteBuffer, generated: bool) -> impl Future<Output = Result<(), FlowControllerError>> + Send {
        (**self).send_packet(packet, generated)
    }

    fn receive_packet(&self, packet: DynamicByteBuffer) -> impl Future<Output = Result<DynamicByteBuffer, FlowControllerError>> + Send {
        (**self).receive_packet(packet)
    }
}

/// Trait for tailor-level cryptographic operations used by flow managers.
pub trait FlowCryptoProvider: Clone + Send {
    /// The identity type used in tailors.
    type Identity: IdentityType + Clone;

    /// Encrypt tailor bytes for sending.
    fn obfuscate_tailor(&mut self, plaintext: DynamicByteBuffer, pool: &crate::bytes::BytePool) -> Result<DynamicByteBuffer, CryptoError>;

    /// Decrypt received tailor bytes.
    fn deobfuscate_tailor(&mut self, ciphertext: DynamicByteBuffer) -> Result<(DynamicByteBuffer, ObfuscationTranscript), CryptoError>;

    /// Verify tailor authentication after deobfuscation.
    fn verify_tailor(&mut self, transcript: ObfuscationTranscript) -> Result<(), CryptoError>;

    /// Overhead added by tailor encryption (nonce + auth tags).
    fn tailor_overhead() -> usize;
}

/// Shared send-side state for flow managers.
pub(crate) struct FlowSendInternal<CP: FlowCryptoProvider> {
    pub(crate) provider: CachedValue<CP>,
    pub(crate) config: FlowConfig,
}

/// Shared receive-side state for flow managers.
pub(crate) struct FlowReceiveInternal<CP: FlowCryptoProvider> {
    pub(crate) provider: CachedValue<CP>,
}

impl<CP: FlowCryptoProvider> FlowSendInternal<CP> {
    /// Encrypt tailor, add fake header and body, return assembled packet ready for socket send.
    pub(crate) async fn prepare_outgoing(&mut self, packet: DynamicByteBuffer, mtu: usize, pool: &crate::bytes::BytePool) -> Result<DynamicByteBuffer, FlowControllerError> {
        let identity_len = <CP::Identity as IdentityType>::length();
        let full_tailor_len = TAILOR_LENGTH + identity_len;
        let (packet_data, packet_tailor) = packet.split_buf(packet.len() - full_tailor_len);
        let packet_flags = PacketFlags::from_bits_truncate(packet_tailor.get(0).clone());
        let encrypted_packet = match self.provider.get_mut().await.map_err(FlowControllerError::MissingCache)?.obfuscate_tailor(packet_tailor, pool) {
            Ok(res) => packet_data.expand_end(res.len()),
            Err(err) => return Err(FlowControllerError::TailorEncryption(err)),
        };

        let fake_header_len = self.config.fake_header_mode.len();
        let full_packet_len = fake_header_len + self.config.fake_body_mode.get_length(mtu, fake_header_len + encrypted_packet.len(), packet_flags.is_service());
        let full_packet = encrypted_packet.expand_start(full_packet_len);

        self.config.fake_header_mode.fill(full_packet.rebuffer_end(fake_header_len));
        get_rng().fill(&mut full_packet.rebuffer_both(fake_header_len, full_packet_len));

        Ok(full_packet)
    }
}

impl<CP: FlowCryptoProvider> FlowReceiveInternal<CP> {
    /// Decrypt tailor, verify, check if discardable. Returns processed packet or None if decoy.
    pub(crate) async fn process_incoming(&mut self, packet: DynamicByteBuffer) -> Result<Option<DynamicByteBuffer>, FlowControllerError> {
        let identity_len = <CP::Identity as IdentityType>::length();
        let full_tailor_len = TAILOR_LENGTH + identity_len;
        let encrypted_tailor_len = identity_len + CP::tailor_overhead();
        let (encrypted_packet, encrypted_tailor) = packet.split_buf(packet.len() - encrypted_tailor_len);
        // Deobfuscation decrypts in-place on the shared underlying buffer.
        // The decrypted tailor sits at the start of the encrypted_tailor region,
        // reachable via encrypted_packet.expand_end(full_tailor_len).
        let tailor = match self.provider.get_mut().await {
            Ok(cipher) => match cipher.deobfuscate_tailor(encrypted_tailor) {
                Ok((tailor, transcript)) => {
                    match cipher.verify_tailor(transcript) {
                        Ok(_) => {}
                        Err(err) => {
                            debug!("error verifying packet tailor: {}", err);
                            return Ok(None);
                        }
                    }
                    tailor
                }
                Err(err) => {
                    debug!("error decrypting packet tailor: {}", err);
                    return Ok(None);
                }
            },
            Err(err) => return Err(FlowControllerError::MissingCache(err)),
        };

        let tailor = Tailor::<CP::Identity>::new(tailor);
        if tailor.flags().is_discardable() {
            info!("decoy packet received, skipping...");
            return Ok(None);
        }

        let payload_len = tailor.payload_length() as usize;
        let is_handshake = tailor.flags().contains(PacketFlags::HANDSHAKE);

        // For handshake packets the entire body is the handshake payload (payload_length=0 is unused).
        // For all other packets, use payload_length to strip fake body/header from the front.
        if is_handshake {
            Ok(Some(encrypted_packet.expand_end(full_tailor_len)))
        } else {
            Ok(Some(encrypted_packet.rebuffer_start(encrypted_packet.len() - payload_len).expand_end(full_tailor_len)))
        }
    }
}
