//! Shared constants, header I/O helpers, and error types for certificate files.

use std::io::{self, Read, Write};
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddr};

use classic_mceliece_rust::{CRYPTO_PUBLICKEYBYTES, CRYPTO_SECRETKEYBYTES};

use crate::bytes::FixedByteBuffer;
use crate::settings::consts::DEFAULT_TYPHOON_ID_LENGTH;
use crate::utils::parse_version;

// ── Stable format constants ──────────────────────────────────────────────────

/// Classic `McEliece` 348864 public key size in bytes.
pub const EPK_BYTES: usize = 261_120;
/// Classic `McEliece` 348864 secret key size in bytes.
pub const ESK_BYTES: usize = 6_492;
/// Ed25519 key size in bytes (signing key, verifying key, or obfuscation key).
pub const ED25519_BYTES: usize = 32;
/// X25519 key size in bytes (public or static secret).
pub const X25519_BYTES: usize = 32;

// Compile-time guards: catch upstream constant drift before it silently corrupts files.
const _: () = assert!(EPK_BYTES == CRYPTO_PUBLICKEYBYTES, "EPK_BYTES must match CRYPTO_PUBLICKEYBYTES");
const _: () = assert!(ESK_BYTES == CRYPTO_SECRETKEYBYTES, "ESK_BYTES must match CRYPTO_SECRETKEYBYTES");
const _: () = assert!(DEFAULT_TYPHOON_ID_LENGTH <= u16::MAX as usize, "DEFAULT_TYPHOON_ID_LENGTH must fit in a u16 for certificate header encoding");

// ── File header constants ────────────────────────────────────────────────────

pub(crate) const MAGIC: &[u8; 7] = b"TYPHOON";
#[cfg(feature = "server")]
pub(crate) const TYPE_SERVER: u8 = b'S';
pub(crate) const TYPE_CLIENT: u8 = b'C';
pub(crate) const FORMAT_VERSION: u8 = 1;

/// Identifies the build flavor: cipher mode (fast/full) crossed with cipher backend
/// (software/hardware). There are only four valid combinations, so both axes are packed into a
/// single byte rather than two: lowercase = fast, uppercase = full; `s`/`S` = software cipher
/// backend, `h`/`H` = hardware. `fast_software`/`fast_hardware` (and likewise
/// `full_software`/`full_hardware`) use different ciphers and nonce lengths (see
/// `crypto::symmetric`), so a mismatch here would silently corrupt the wire format rather than
/// fail cleanly.
#[cfg(feature = "fast_software")]
pub(crate) const FLAVOR_BYTE: u8 = b's';
#[cfg(feature = "fast_hardware")]
pub(crate) const FLAVOR_BYTE: u8 = b'h';
#[cfg(feature = "full_software")]
pub(crate) const FLAVOR_BYTE: u8 = b'S';
#[cfg(feature = "full_hardware")]
pub(crate) const FLAVOR_BYTE: u8 = b'H';

/// The protocol major version of the running build, parsed from `CARGO_PKG_VERSION`.
/// Shares its parsing logic with the handshake's client/server version check
/// (see `defaults::DefaultClientConnectionHandler`/`DefaultServerConnectionHandler`).
fn local_protocol_major_version() -> u32 {
    parse_version(env!("CARGO_PKG_VERSION").as_bytes()).0 as u32
}

// ── CertificateError ─────────────────────────────────────────────────────────

/// Error type for certificate file operations.
#[derive(Debug, thiserror::Error)]
pub enum CertificateError {
    /// Reading or writing the certificate file failed at the OS level.
    #[error("I/O error: {0}")]
    Io(#[from] io::Error),
    /// The file does not start with the expected `TYPHOON` magic bytes.
    #[error("invalid file: bad magic bytes")]
    InvalidMagic,
    /// The file's record type byte doesn't match what the caller expected (server key pair vs. client certificate).
    #[error("invalid file type: expected '{expected}', got '{got}'")]
    InvalidType {
        /// The record type the caller expected (`'S'` or `'C'`).
        expected: char,
        /// The record type actually found in the file.
        got: char,
    },
    /// The file was written under a different build flavor (cipher mode and/or cipher backend) than the one currently active.
    #[error("build flavor mismatch: file was written for a different cipher mode/backend")]
    FlavorMismatch,
    /// The file's format version byte is not supported by this version of the crate.
    #[error("unsupported format version: {0}")]
    UnsupportedVersion(u8),
    /// The file was generated by a build with a different protocol major version.
    #[error("protocol version mismatch: local build is v{local}, certificate was generated by v{certificate}")]
    VersionMismatch {
        /// The protocol major version of the running build.
        local: u32,
        /// The protocol major version embedded in the certificate file.
        certificate: u32,
    },
    /// The file was generated by a build using a different `ID` field length.
    #[error("identity length mismatch: local build uses {local}-byte identities, certificate was generated with {certificate}-byte identities")]
    IdLengthMismatch {
        /// The `ID` field length (bytes) of the running build.
        local: usize,
        /// The `ID` field length (bytes) embedded in the certificate file.
        certificate: usize,
    },
    /// The key material in the file is malformed or of unexpected length.
    #[error("invalid key data in file")]
    InvalidKeyData,
    /// A client certificate was built with an empty address list.
    #[error("certificate contains no server addresses")]
    NoAddresses,
}

// ── Header I/O ────────────────────────────────────────────────────────────────

/// Write the file header: magic, record type, build-flavor byte, format version, and the
/// non-negotiable protocol settings of the running build (major version, `ID` length). See
/// [`read_header`] for how these are validated on load.
pub(crate) fn write_header(w: &mut impl Write, record_type: u8) -> Result<(), io::Error> {
    w.write_all(MAGIC)?;
    w.write_all(&[record_type, FLAVOR_BYTE, FORMAT_VERSION])?;
    w.write_all(&local_protocol_major_version().to_be_bytes())?;
    w.write_all(&(DEFAULT_TYPHOON_ID_LENGTH as u16).to_be_bytes())
}

/// Read and validate the file header written by [`write_header`].
///
/// Beyond magic/type/format-version checks, this enforces that every setting which is fixed at
/// compile time and cannot be renegotiated at runtime — build flavor, protocol major version, and
/// `ID` length — matches between the running build and the build that produced this
/// certificate/key file. A mismatch on any of these would otherwise corrupt the wire format
/// rather than fail cleanly, since neither side can detect it from the handshake alone.
pub(crate) fn read_header(r: &mut impl Read, expected_type: u8) -> Result<(), CertificateError> {
    let mut magic = [0u8; 7];
    r.read_exact(&mut magic)?;
    if &magic != MAGIC {
        return Err(CertificateError::InvalidMagic);
    }

    let mut header = [0u8; 3];
    r.read_exact(&mut header)?;
    let [record_type, flavor, version] = header;
    if record_type != expected_type {
        return Err(CertificateError::InvalidType {
            expected: expected_type as char,
            got: record_type as char,
        });
    }
    // Check the format version before interpreting any field introduced after it, so an
    // older-format file (whose trailing bytes are payload, not header fields) is reported as
    // UnsupportedVersion rather than misread as a bogus setting mismatch.
    if version != FORMAT_VERSION {
        return Err(CertificateError::UnsupportedVersion(version));
    }
    if flavor != FLAVOR_BYTE {
        return Err(CertificateError::FlavorMismatch);
    }

    let mut major_bytes = [0u8; 4];
    r.read_exact(&mut major_bytes)?;
    let certificate_major = u32::from_be_bytes(major_bytes);
    let local_major = local_protocol_major_version();
    if certificate_major != local_major {
        return Err(CertificateError::VersionMismatch {
            local: local_major,
            certificate: certificate_major,
        });
    }

    let mut id_len_bytes = [0u8; 2];
    r.read_exact(&mut id_len_bytes)?;
    let certificate_id_length = u16::from_be_bytes(id_len_bytes) as usize;
    if certificate_id_length != DEFAULT_TYPHOON_ID_LENGTH {
        return Err(CertificateError::IdLengthMismatch {
            local: DEFAULT_TYPHOON_ID_LENGTH,
            certificate: certificate_id_length,
        });
    }

    Ok(())
}

// ── Address I/O ───────────────────────────────────────────────────────────────

pub(crate) fn write_addresses(w: &mut impl Write, addrs: &[SocketAddr]) -> Result<(), io::Error> {
    w.write_all(&(addrs.len() as u16).to_be_bytes())?;
    for addr in addrs {
        match addr.ip() {
            IpAddr::V4(ip) => {
                w.write_all(&[4u8])?;
                w.write_all(&ip.octets())?;
            }
            IpAddr::V6(ip) => {
                w.write_all(&[6u8])?;
                w.write_all(&ip.octets())?;
            }
        }
        w.write_all(&addr.port().to_be_bytes())?;
    }
    Ok(())
}

pub(crate) fn read_addresses(r: &mut impl Read) -> Result<Vec<SocketAddr>, CertificateError> {
    let mut count_bytes = [0u8; 2];
    r.read_exact(&mut count_bytes)?;
    let count = u16::from_be_bytes(count_bytes) as usize;
    let mut addrs = Vec::with_capacity(count);
    for _ in 0..count {
        let mut family = [0u8; 1];
        r.read_exact(&mut family)?;
        let ip = match family[0] {
            4 => {
                let mut octets = [0u8; 4];
                r.read_exact(&mut octets)?;
                IpAddr::V4(Ipv4Addr::from(octets))
            }
            6 => {
                let mut octets = [0u8; 16];
                r.read_exact(&mut octets)?;
                IpAddr::V6(Ipv6Addr::from(octets))
            }
            _ => return Err(CertificateError::InvalidKeyData),
        };
        let mut port_bytes = [0u8; 2];
        r.read_exact(&mut port_bytes)?;
        addrs.push(SocketAddr::new(ip, u16::from_be_bytes(port_bytes)));
    }
    Ok(addrs)
}

// ── ObfuscationBufferContainer ────────────────────────────────────────────────

/// Trait for types containing obfuscation key material.
pub(crate) trait ObfuscationBufferContainer {
    /// Get obfuscation buffer (OBFS in fast mode, OPK bytes in full mode).
    fn obfuscation_buffer(&self) -> FixedByteBuffer<ED25519_BYTES>;
}
