name: Features

permissions:
  contents: read

on:
  push:
    paths:
      - 'typhoon/**'
      - '.github/workflows/rust.yaml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  typhoon-crate-build:
    name: Build and Test TYPHOON Rust Crate
    runs-on: ${{ matrix.architecture.image }}
    strategy:
      fail-fast: false
      matrix:
        crypto-impl:
          - fast_software
          - fast_hardware
          - full_software
          - full_hardware
        protocol-part:
          - server
          - client
          - server,client
        asynchronous-lib:
          - async-std
          - tokio
        debug-impl:
          - 'debug'
          - ''
        architecture:
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - image: windows-2025
            target: x86_64-pc-windows-msvc
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - image: windows-11-arm
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Rust 🦀
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.89.0"
          target: ${{ matrix.architecture.target }}
          rust-src-dir: typhoon
          override: true

      - name: Build TYPHOON Crate 🏗️
        working-directory: typhoon
        run: cargo build --no-default-features --features ${{ matrix.crypto-impl }},${{ matrix.protocol-part }},${{ matrix.asynchronous-lib }},${{ matrix.debug-impl }}

      - name: Test TYPHOON Crate 🧪
        working-directory: typhoon
        run: cargo test --no-default-features --features ${{ matrix.crypto-impl }},${{ matrix.protocol-part }},${{ matrix.asynchronous-lib }},${{ matrix.debug-impl }}
