name: Features

permissions:
  contents: read

on:
  push:
    paths:
      - 'typhoon/**'
      - '.github/workflows/features.yaml'
      - '.github/scripts/test_matrix.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  typhoon-crate-build:
    name: Build and Test TYPHOON Rust Crate (${{ matrix.architecture.image }})
    runs-on: ${{ matrix.architecture.image }}
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - image: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - image: windows-2025
            target: x86_64-pc-windows-msvc
          - image: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - image: windows-11-arm
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Rust 🦀
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.89.0"
          target: ${{ matrix.architecture.target }}
          rust-src-dir: typhoon
          override: true

      - name: Run all feature combinations 🧪
        working-directory: typhoon
        shell: bash
        run: bash ../.github/scripts/test_matrix.sh
