name: Lint

permissions:
  contents: read

on:
  push:
    paths:
      - 'typhoon/**'
      - 'evaluation/**'
      - '.github/workflows/lint.yaml'
      - '.shellcheckrc'
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  all-lint:
    name: Lint All the Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Rust 🦀
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt, clippy
          rust-src-dir: typhoon
          override: true

      - name: Setup Python 🐍
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.12"

      - name: Check formatting 🎨
        working-directory: typhoon
        run: cargo fmt --check

      - name: Run clippy 📎
        working-directory: typhoon
        run: cargo clippy

      - name: Check shell scripts 🐚
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: "."

      - name: Check Dockerfile configuration 📦
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
          config: evaluation/.hadolint.yaml

      - name: Check Python code 📜
        uses: astral-sh/ruff-action@v3
        with:
          args: "check evaluation/src evaluation/protocols"

      - name: Lint markdown 📝
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: '**/*.md'
